# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: dev.krillmeister.se
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'pladder-snaas'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '--format docker' # needed for podman/buildah
  - job: Push
    displayName: Push
    pool: dev.krillmeister.se
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'pladder-snaas'
        command: push

