# For development use
version: "3"
services:
  snaas:
    restart: always
    build:
      context: "."
    ports:
      - "8080:8080"
    environment:
      - "uri=https://pladder.example/api/run-command"
      - "token=ABC123"
