name: CI

on:
  workflow_dispatch:

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/krillmeister/pladder-SnaaS
            azure-pipeline-name: 'deploy-prod'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
